import re
from ..parsers.gnc_parser import GNCSheet, GNCPart, GNCContour, GNCCommand


class GNCGenerator:
    def __init__(self):
        self.contour_counter = 1
        self.n_code_counter = 1005
        self.n_code_step = 5

    def _apply_offsets(self, line_text: str, offset_x: float, offset_y: float) -> str:
        """
        Apply X and Y offsets to coordinates in the line.
        Assumes absolute positioning (G90).
        """
        if offset_x == 0 and offset_y == 0:
            return line_text

        # Regex to find X and Y values
        def replace_coord(match):
            axis = match.group(1).upper()
            val_str = match.group(2)
            try:
                val = float(val_str)
                if axis == 'X':
                    return f"X{val + offset_x:.3f}"
                elif axis == 'Y':
                    return f"Y{val + offset_y:.3f}"
            except ValueError:
                pass
            return match.group(0)

        # Replace X
        if offset_x != 0:
            line_text = re.sub(r'([X])([+-]?\d*\.?\d+)', replace_coord, line_text, flags=re.IGNORECASE)
        
        # Replace Y
        if offset_y != 0:
            line_text = re.sub(r'([Y])([+-]?\d*\.?\d+)', replace_coord, line_text, flags=re.IGNORECASE)
            
        return line_text

    def _renumber_line(self, line_text: str) -> str:
        """
        Renumber CONTOUR IDs and N-codes globally.
        """
        # 1. Renumber Contours: (==== CONTOUR  X ====)
        if "(==== CONTOUR" in line_text.upper():
            line_text = re.sub(r'\(={4,}\s*CONTOUR\s+\d+\s+={4,}\)', 
                               f"(==== CONTOUR  {self.contour_counter} ====)", 
                               line_text, flags=re.IGNORECASE)
            self.contour_counter += 1
            return line_text

        # 2. Renumber N-codes: N1005 ... SSD[SD.Cr_Nb1=1005]
        if line_text.strip().startswith('N') or "SSD[SD.Cr_Nb1=" in line_text:
            # Replace N code
            new_n = self.n_code_counter
            line_text = re.sub(r'^N\d+', f"N{new_n}", line_text.strip())
            
            # Replace SSD Cr_Nb1 if present
            line_text = re.sub(r'SSD\[SD\.Cr_Nb1=\d+\]', f"SSD[SD.Cr_Nb1={new_n}]", line_text)
            
            self.n_code_counter += self.n_code_step
            return line_text

        return line_text

    def generate(self, sheet: GNCSheet) -> str:
        """
        Reconstructs the GNC file content from the GNCSheet object.
        Applies updates from metadata and performs global renumbering.
        """
        self.contour_counter = 1
        
        # Initialize N-code from metadata or default
        self.n_code_counter = sheet.metadata.get('n_code_start', 1005)
        self.n_code_step = sheet.metadata.get('n_code_step', 5)
        
        lines = []

        # 1. Headers
        if sheet.header_commands:
            for cmd in sheet.header_commands:
                lines.append(cmd.original_text)
        else:
            # Fallback Template
            lines.append(f"(Generated by DocuFlow GNC Editor)")
            if sheet.metadata.get('model'):
                lines.append(f"(*MODEL {sheet.metadata['model']})")
            if sheet.program_width and sheet.program_height:
                lines.append(f"(*SHEET {sheet.program_width} {sheet.program_height} {sheet.thickness or 0} {sheet.cut_count or 1} 1 0.0 0.0 )")
            lines.append("G71 G90")
            lines.append("CALL P999998")
            lines.append("G54")

        # 2. Parts
        for part in sheet.parts:
            # Part separator
            lines.append("(*****Part info*****)")
            lines.append(f"(PART NAME:{part.name or 'UNKNOWN'})")

            offset_x = getattr(part, 'x', 0.0) or 0.0
            offset_y = getattr(part, 'y', 0.0) or 0.0

            for contour in part.contours:
                for cmd in contour.commands:
                    line_text = cmd.original_text
                    if not line_text:
                        continue

                    # Skip redundant Part Info/Contour lines if they are already in the stream 
                    # from parsing, because we generate them explicitly above.
                    if "(PART NAME:" in line_text.upper():
                        continue

                    # Update SHEET line if present (in case it was in header_commands or part metadata)
                    if "(*SHEET" in line_text.upper():
                         if sheet.program_width is not None and sheet.program_height is not None:
                            param_5 = sheet.metadata.get('sheet_param_5', '1')
                            param_6 = sheet.metadata.get('sheet_param_6', '0.0')
                            param_7 = sheet.metadata.get('sheet_param_7', '0.0')
                            line_text = f"(*SHEET {sheet.program_width} {sheet.program_height} {sheet.thickness or 0} {sheet.cut_count or 1} {param_5} {param_6} {param_7} )"

                    # Renumber
                    line_text = self._renumber_line(line_text)

                    # Apply Coordinate Offsets
                    if cmd.type not in ["METADATA", "COMMENT", "HEADER"]:
                        line_text = self._apply_offsets(line_text, offset_x, offset_y)

                    lines.append(line_text)

        return "\n".join(lines)
