"""
Tests for the deduplicated SVG placeholder writer in svg_generator.
"""

import xml.etree.ElementTree as ET
from pathlib import Path


def test_placeholder_svg_helper_exists() -> None:
    """A shared placeholder SVG writer must exist to avoid duplication."""
    from docuflow.infrastructure.graphics import svg_generator

    assert hasattr(svg_generator, "write_placeholder_svg"), (
        "svg_generator must expose a single shared write_placeholder_svg function"
    )


def test_placeholder_svg_produces_valid_xml(tmp_path: Path) -> None:
    """Placeholder SVG output must be parseable XML."""
    from docuflow.infrastructure.graphics.svg_generator import write_placeholder_svg

    out = tmp_path / "placeholder.svg"
    write_placeholder_svg(out, label="TEST")
    content = out.read_text(encoding="utf-8")
    ET.fromstring(content)  # noqa: S314  # trusted SVG content generated by us


def test_placeholder_svg_contains_label(tmp_path: Path) -> None:
    """The placeholder SVG must embed the given label text."""
    from docuflow.infrastructure.graphics.svg_generator import write_placeholder_svg

    out = tmp_path / "placeholder.svg"
    write_placeholder_svg(out, label="No Data")
    content = out.read_text(encoding="utf-8")
    assert "No Data" in content


def test_placeholder_svg_default_label(tmp_path: Path) -> None:
    """write_placeholder_svg must work with a default (empty) label."""
    from docuflow.infrastructure.graphics.svg_generator import write_placeholder_svg

    out = tmp_path / "default.svg"
    write_placeholder_svg(out)  # no label argument
    content = out.read_text(encoding="utf-8")
    ET.fromstring(content)  # noqa: S314  # trusted SVG content generated by us


def test_generate_thumbnail_none_uses_helper(tmp_path: Path) -> None:
    """generate_thumbnail with None part must produce parseable SVG."""
    from docuflow.infrastructure.graphics.svg_generator import SVGGenerator

    gen = SVGGenerator()
    out = str(tmp_path / "out.svg")
    result = gen.generate_thumbnail(part=None, output_path=out)
    assert result == (0, 0)
    content = (tmp_path / "out.svg").read_text(encoding="utf-8")
    ET.fromstring(content)  # noqa: S314  # trusted SVG content generated by us


def test_generate_thumbnail_empty_contours_uses_helper(tmp_path: Path) -> None:
    """generate_thumbnail with an empty-contours part must produce parseable SVG.

    A part with no contours at all triggers the placeholder path.
    (A part with contours that have no commands hits the fallback bounds path,
    which still renders a real SVG.)
    """
    from docuflow.features.folder_scanner.parsers.gnc import GncPartData
    from docuflow.infrastructure.graphics.svg_generator import SVGGenerator

    # Part with an empty contours list → triggers write_placeholder_svg("No Data")
    part = GncPartData(sku="EMPTY", contours=[])
    gen = SVGGenerator()
    out = str(tmp_path / "empty.svg")
    result = gen.generate_thumbnail(part=part, output_path=out)
    assert result == (0, 0)
    content = (tmp_path / "empty.svg").read_text(encoding="utf-8")
    ET.fromstring(content)  # noqa: S314  # trusted SVG content generated by us
    assert "No Data" in content
